// Extended unit configuration for Age of Empires 2 Web

export interface UnitConfig {
  name: string
  type: string
  category: 'civilian' | 'infantry' | 'archer' | 'cavalry' | 'siege' | 'monk' | 'naval'
  age: 'dark_age' | 'feudal_age' | 'castle_age' | 'imperial_age'
  hp: number
  attack: number
  meleeArmor: number
  pierceArmor: number
  speed: number
  range?: number
  attackSpeed: number // attacks per second
  lineOfSight: number
  cost: {
    food?: number
    wood?: number
    gold?: number
  }
  trainTime: number // seconds
  population: number
  trainingBuilding: string
  upgradeTo?: string
  strong_against?: string[]
  weak_against?: string[]
}

export const UNITS: Record<string, UnitConfig> = {
  // CIVILIAN UNITS
  villager: {
    name: 'Villager',
    type: 'villager',
    category: 'civilian',
    age: 'dark_age',
    hp: 25,
    attack: 3,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 0.8,
    attackSpeed: 2.0,
    lineOfSight: 4,
    cost: { food: 50 },
    trainTime: 25,
    population: 1,
    trainingBuilding: 'town_center',
  },

  // INFANTRY - MILITIA LINE
  militia: {
    name: 'Militia',
    type: 'militia',
    category: 'infantry',
    age: 'dark_age',
    hp: 40,
    attack: 4,
    meleeArmor: 0,
    pierceArmor: 1,
    speed: 0.9,
    attackSpeed: 2.0,
    lineOfSight: 4,
    cost: { food: 60, gold: 20 },
    trainTime: 21,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'man_at_arms',
    strong_against: ['eagle_warrior', 'building'],
    weak_against: ['archer', 'cavalry_archer', 'cataphract'],
  },

  man_at_arms: {
    name: 'Man-at-Arms',
    type: 'man_at_arms',
    category: 'infantry',
    age: 'feudal_age',
    hp: 45,
    attack: 6,
    meleeArmor: 0,
    pierceArmor: 1,
    speed: 0.9,
    attackSpeed: 2.0,
    lineOfSight: 4,
    cost: { food: 60, gold: 20 },
    trainTime: 21,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'long_swordsman',
    strong_against: ['eagle_warrior', 'building'],
    weak_against: ['archer', 'cavalry_archer', 'knight'],
  },

  long_swordsman: {
    name: 'Long Swordsman',
    type: 'long_swordsman',
    category: 'infantry',
    age: 'castle_age',
    hp: 60,
    attack: 9,
    meleeArmor: 0,
    pierceArmor: 1,
    speed: 0.9,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { food: 60, gold: 20 },
    trainTime: 21,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'two_handed_swordsman',
    strong_against: ['eagle_warrior', 'building'],
    weak_against: ['archer', 'cavalry_archer', 'knight'],
  },

  two_handed_swordsman: {
    name: 'Two-Handed Swordsman',
    type: 'two_handed_swordsman',
    category: 'infantry',
    age: 'imperial_age',
    hp: 60,
    attack: 12,
    meleeArmor: 0,
    pierceArmor: 1,
    speed: 0.9,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { food: 60, gold: 20 },
    trainTime: 21,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'champion',
    strong_against: ['eagle_warrior', 'building'],
    weak_against: ['archer', 'cavalry_archer', 'knight'],
  },

  champion: {
    name: 'Champion',
    type: 'champion',
    category: 'infantry',
    age: 'imperial_age',
    hp: 70,
    attack: 13,
    meleeArmor: 1,
    pierceArmor: 1,
    speed: 0.9,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { food: 60, gold: 20 },
    trainTime: 21,
    population: 1,
    trainingBuilding: 'barracks',
    strong_against: ['eagle_warrior', 'building', 'siege'],
    weak_against: ['archer', 'cavalry_archer', 'knight'],
  },

  // INFANTRY - SPEARMAN LINE
  spearman: {
    name: 'Spearman',
    type: 'spearman',
    category: 'infantry',
    age: 'feudal_age',
    hp: 45,
    attack: 3,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 1.0,
    attackSpeed: 3.0,
    lineOfSight: 4,
    cost: { food: 35, wood: 25 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'pikeman',
    strong_against: ['knight', 'camel', 'elephant', 'cavalry'],
    weak_against: ['archer', 'cataphract', 'jaguar_warrior'],
  },

  pikeman: {
    name: 'Pikeman',
    type: 'pikeman',
    category: 'infantry',
    age: 'castle_age',
    hp: 55,
    attack: 4,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 1.0,
    attackSpeed: 3.0,
    lineOfSight: 4,
    cost: { food: 35, wood: 25 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'halberdier',
    strong_against: ['knight', 'camel', 'elephant', 'war_elephant'],
    weak_against: ['archer', 'cataphract', 'jaguar_warrior'],
  },

  halberdier: {
    name: 'Halberdier',
    type: 'halberdier',
    category: 'infantry',
    age: 'imperial_age',
    hp: 60,
    attack: 6,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 1.0,
    attackSpeed: 3.0,
    lineOfSight: 4,
    cost: { food: 35, wood: 25 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'barracks',
    strong_against: ['knight', 'paladin', 'war_elephant', 'cavalry'],
    weak_against: ['archer', 'cataphract', 'jaguar_warrior'],
  },

  // INFANTRY - EAGLE WARRIOR LINE
  eagle_scout: {
    name: 'Eagle Scout',
    type: 'eagle_scout',
    category: 'infantry',
    age: 'feudal_age',
    hp: 50,
    attack: 4,
    meleeArmor: 0,
    pierceArmor: 2,
    speed: 1.1,
    attackSpeed: 2.0,
    lineOfSight: 6,
    cost: { food: 20, gold: 50 },
    trainTime: 60,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'eagle_warrior',
    strong_against: ['monk', 'archer', 'siege'],
    weak_against: ['knight', 'champion', 'hand_cannoneer'],
  },

  eagle_warrior: {
    name: 'Eagle Warrior',
    type: 'eagle_warrior',
    category: 'infantry',
    age: 'castle_age',
    hp: 55,
    attack: 7,
    meleeArmor: 0,
    pierceArmor: 3,
    speed: 1.2,
    attackSpeed: 2.0,
    lineOfSight: 6,
    cost: { food: 20, gold: 50 },
    trainTime: 60,
    population: 1,
    trainingBuilding: 'barracks',
    upgradeTo: 'elite_eagle_warrior',
    strong_against: ['monk', 'archer', 'siege', 'cavalry_archer'],
    weak_against: ['knight', 'champion', 'hand_cannoneer'],
  },

  elite_eagle_warrior: {
    name: 'Elite Eagle Warrior',
    type: 'elite_eagle_warrior',
    category: 'infantry',
    age: 'imperial_age',
    hp: 60,
    attack: 9,
    meleeArmor: 0,
    pierceArmor: 4,
    speed: 1.3,
    attackSpeed: 2.0,
    lineOfSight: 6,
    cost: { food: 20, gold: 50 },
    trainTime: 60,
    population: 1,
    trainingBuilding: 'barracks',
    strong_against: ['monk', 'archer', 'siege', 'cavalry_archer'],
    weak_against: ['knight', 'champion', 'hand_cannoneer'],
  },

  // ARCHERS
  archer: {
    name: 'Archer',
    type: 'archer',
    category: 'archer',
    age: 'feudal_age',
    hp: 30,
    attack: 4,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 0.96,
    range: 4,
    attackSpeed: 2.0,
    lineOfSight: 6,
    cost: { wood: 25, gold: 45 },
    trainTime: 35,
    population: 1,
    trainingBuilding: 'archery_range',
    upgradeTo: 'crossbowman',
    strong_against: ['spearman', 'eagle_warrior', 'skirmisher'],
    weak_against: ['skirmisher', 'knight', 'huskarl', 'eagle_warrior'],
  },

  crossbowman: {
    name: 'Crossbowman',
    type: 'crossbowman',
    category: 'archer',
    age: 'castle_age',
    hp: 35,
    attack: 5,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 0.96,
    range: 5,
    attackSpeed: 2.0,
    lineOfSight: 7,
    cost: { wood: 25, gold: 45 },
    trainTime: 27,
    population: 1,
    trainingBuilding: 'archery_range',
    upgradeTo: 'arbalest',
    strong_against: ['spearman', 'infantry', 'skirmisher'],
    weak_against: ['skirmisher', 'knight', 'huskarl', 'eagle_warrior'],
  },

  arbalest: {
    name: 'Arbalester',
    type: 'arbalest',
    category: 'archer',
    age: 'imperial_age',
    hp: 40,
    attack: 6,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 0.96,
    range: 5,
    attackSpeed: 2.0,
    lineOfSight: 7,
    cost: { wood: 25, gold: 45 },
    trainTime: 27,
    population: 1,
    trainingBuilding: 'archery_range',
    strong_against: ['spearman', 'infantry', 'skirmisher'],
    weak_against: ['skirmisher', 'knight', 'huskarl', 'eagle_warrior'],
  },

  skirmisher: {
    name: 'Skirmisher',
    type: 'skirmisher',
    category: 'archer',
    age: 'feudal_age',
    hp: 30,
    attack: 2,
    meleeArmor: 0,
    pierceArmor: 3,
    speed: 0.96,
    range: 4,
    attackSpeed: 3.0,
    lineOfSight: 6,
    cost: { food: 25, wood: 35 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'archery_range',
    upgradeTo: 'elite_skirmisher',
    strong_against: ['archer', 'cavalry_archer'],
    weak_against: ['knight', 'militia', 'eagle_warrior'],
  },

  elite_skirmisher: {
    name: 'Elite Skirmisher',
    type: 'elite_skirmisher',
    category: 'archer',
    age: 'castle_age',
    hp: 35,
    attack: 3,
    meleeArmor: 0,
    pierceArmor: 4,
    speed: 0.96,
    range: 5,
    attackSpeed: 3.0,
    lineOfSight: 7,
    cost: { food: 25, wood: 35 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'archery_range',
    strong_against: ['archer', 'cavalry_archer'],
    weak_against: ['knight', 'militia', 'eagle_warrior'],
  },

  // CAVALRY ARCHERS
  cavalry_archer: {
    name: 'Cavalry Archer',
    type: 'cavalry_archer',
    category: 'archer',
    age: 'castle_age',
    hp: 50,
    attack: 6,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 1.4,
    range: 4,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { wood: 40, gold: 60 },
    trainTime: 34,
    population: 1,
    trainingBuilding: 'archery_range',
    upgradeTo: 'heavy_cavalry_archer',
    strong_against: ['infantry', 'siege'],
    weak_against: ['skirmisher', 'camel', 'eagle_warrior'],
  },

  heavy_cavalry_archer: {
    name: 'Heavy Cavalry Archer',
    type: 'heavy_cavalry_archer',
    category: 'archer',
    age: 'imperial_age',
    hp: 60,
    attack: 7,
    meleeArmor: 1,
    pierceArmor: 0,
    speed: 1.4,
    range: 4,
    attackSpeed: 2.0,
    lineOfSight: 6,
    cost: { wood: 40, gold: 60 },
    trainTime: 27,
    population: 1,
    trainingBuilding: 'archery_range',
    strong_against: ['infantry', 'siege'],
    weak_against: ['skirmisher', 'camel', 'eagle_warrior'],
  },

  hand_cannoneer: {
    name: 'Hand Cannoneer',
    type: 'hand_cannoneer',
    category: 'archer',
    age: 'imperial_age',
    hp: 35,
    attack: 17,
    meleeArmor: 1,
    pierceArmor: 0,
    speed: 0.96,
    range: 7,
    attackSpeed: 3.45,
    lineOfSight: 9,
    cost: { food: 45, gold: 50 },
    trainTime: 34,
    population: 1,
    trainingBuilding: 'archery_range',
    strong_against: ['infantry', 'eagle_warrior', 'building'],
    weak_against: ['skirmisher', 'cavalry', 'huskarl'],
  },

  // CAVALRY - SCOUT LINE
  scout_cavalry: {
    name: 'Scout Cavalry',
    type: 'scout_cavalry',
    category: 'cavalry',
    age: 'feudal_age',
    hp: 45,
    attack: 3,
    meleeArmor: 0,
    pierceArmor: 2,
    speed: 1.55,
    attackSpeed: 2.0,
    lineOfSight: 4,
    cost: { food: 80 },
    trainTime: 30,
    population: 1,
    trainingBuilding: 'stable',
    upgradeTo: 'light_cavalry',
    strong_against: ['monk', 'archer', 'siege'],
    weak_against: ['spearman', 'camel', 'knight'],
  },

  light_cavalry: {
    name: 'Light Cavalry',
    type: 'light_cavalry',
    category: 'cavalry',
    age: 'castle_age',
    hp: 60,
    attack: 7,
    meleeArmor: 0,
    pierceArmor: 2,
    speed: 1.5,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { food: 80 },
    trainTime: 30,
    population: 1,
    trainingBuilding: 'stable',
    upgradeTo: 'hussar',
    strong_against: ['monk', 'archer', 'siege'],
    weak_against: ['spearman', 'camel', 'knight'],
  },

  hussar: {
    name: 'Hussar',
    type: 'hussar',
    category: 'cavalry',
    age: 'imperial_age',
    hp: 75,
    attack: 7,
    meleeArmor: 0,
    pierceArmor: 2,
    speed: 1.5,
    attackSpeed: 1.9,
    lineOfSight: 6,
    cost: { food: 80 },
    trainTime: 30,
    population: 1,
    trainingBuilding: 'stable',
    strong_against: ['monk', 'archer', 'siege'],
    weak_against: ['spearman', 'camel', 'knight'],
  },

  // CAVALRY - KNIGHT LINE
  knight: {
    name: 'Knight',
    type: 'knight',
    category: 'cavalry',
    age: 'castle_age',
    hp: 100,
    attack: 10,
    meleeArmor: 2,
    pierceArmor: 2,
    speed: 1.35,
    attackSpeed: 1.8,
    lineOfSight: 4,
    cost: { food: 60, gold: 75 },
    trainTime: 30,
    population: 1,
    trainingBuilding: 'stable',
    upgradeTo: 'cavalier',
    strong_against: ['archer', 'infantry', 'siege'],
    weak_against: ['spearman', 'camel', 'monk'],
  },

  cavalier: {
    name: 'Cavalier',
    type: 'cavalier',
    category: 'cavalry',
    age: 'imperial_age',
    hp: 120,
    attack: 12,
    meleeArmor: 2,
    pierceArmor: 2,
    speed: 1.35,
    attackSpeed: 1.8,
    lineOfSight: 4,
    cost: { food: 60, gold: 75 },
    trainTime: 30,
    population: 1,
    trainingBuilding: 'stable',
    upgradeTo: 'paladin',
    strong_against: ['archer', 'infantry', 'siege'],
    weak_against: ['spearman', 'camel', 'monk'],
  },

  paladin: {
    name: 'Paladin',
    type: 'paladin',
    category: 'cavalry',
    age: 'imperial_age',
    hp: 160,
    attack: 14,
    meleeArmor: 2,
    pierceArmor: 3,
    speed: 1.35,
    attackSpeed: 1.9,
    lineOfSight: 5,
    cost: { food: 60, gold: 75 },
    trainTime: 30,
    population: 1,
    trainingBuilding: 'stable',
    strong_against: ['archer', 'infantry', 'siege'],
    weak_against: ['spearman', 'camel', 'monk'],
  },

  // CAVALRY - CAMEL LINE
  camel: {
    name: 'Camel',
    type: 'camel',
    category: 'cavalry',
    age: 'castle_age',
    hp: 100,
    attack: 5,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 1.45,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { food: 55, gold: 60 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'stable',
    upgradeTo: 'heavy_camel',
    strong_against: ['knight', 'cavalry', 'war_elephant'],
    weak_against: ['archer', 'infantry'],
  },

  heavy_camel: {
    name: 'Heavy Camel',
    type: 'heavy_camel',
    category: 'cavalry',
    age: 'imperial_age',
    hp: 120,
    attack: 7,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 1.45,
    attackSpeed: 2.0,
    lineOfSight: 5,
    cost: { food: 55, gold: 60 },
    trainTime: 22,
    population: 1,
    trainingBuilding: 'stable',
    strong_against: ['knight', 'cavalry', 'war_elephant', 'paladin'],
    weak_against: ['archer', 'infantry'],
  },

  // MONK
  monk: {
    name: 'Monk',
    type: 'monk',
    category: 'monk',
    age: 'castle_age',
    hp: 30,
    attack: 0,
    meleeArmor: 0,
    pierceArmor: 0,
    speed: 0.7,
    range: 9,
    attackSpeed: 0, // Special conversion mechanic
    lineOfSight: 11,
    cost: { gold: 100 },
    trainTime: 51,
    population: 1,
    trainingBuilding: 'monastery',
    strong_against: ['cavalry', 'knight', 'siege'],
    weak_against: ['archer', 'eagle_warrior', 'huskarl'],
  },

  // SIEGE
  battering_ram: {
    name: 'Battering Ram',
    type: 'battering_ram',
    category: 'siege',
    age: 'castle_age',
    hp: 175,
    attack: 2,
    meleeArmor: -3,
    pierceArmor: 180,
    speed: 0.5,
    attackSpeed: 5.0,
    lineOfSight: 3,
    cost: { wood: 160, gold: 75 },
    trainTime: 36,
    population: 1,
    trainingBuilding: 'siege_workshop',
    upgradeTo: 'capped_ram',
    strong_against: ['building', 'wall'],
    weak_against: ['infantry', 'archer'],
  },

  mangonel: {
    name: 'Mangonel',
    type: 'mangonel',
    category: 'siege',
    age: 'castle_age',
    hp: 50,
    attack: 40,
    meleeArmor: 0,
    pierceArmor: 6,
    speed: 0.6,
    range: 7,
    attackSpeed: 6.0,
    lineOfSight: 9,
    cost: { wood: 160, gold: 135 },
    trainTime: 46,
    population: 3,
    trainingBuilding: 'siege_workshop',
    upgradeTo: 'onager',
    strong_against: ['infantry', 'archer', 'building'],
    weak_against: ['cavalry', 'knight', 'eagle_warrior'],
  },

  onager: {
    name: 'Onager',
    type: 'onager',
    category: 'siege',
    age: 'imperial_age',
    hp: 60,
    attack: 50,
    meleeArmor: 0,
    pierceArmor: 7,
    speed: 0.6,
    range: 8,
    attackSpeed: 6.0,
    lineOfSight: 9,
    cost: { wood: 160, gold: 135 },
    trainTime: 46,
    population: 3,
    trainingBuilding: 'siege_workshop',
    strong_against: ['infantry', 'archer', 'building'],
    weak_against: ['cavalry', 'knight', 'eagle_warrior'],
  },

  scorpion: {
    name: 'Scorpion',
    type: 'scorpion',
    category: 'siege',
    age: 'castle_age',
    hp: 40,
    attack: 12,
    meleeArmor: 0,
    pierceArmor: 7,
    speed: 0.65,
    range: 7,
    attackSpeed: 3.6,
    lineOfSight: 9,
    cost: { wood: 75, gold: 75 },
    trainTime: 30,
    population: 2,
    trainingBuilding: 'siege_workshop',
    upgradeTo: 'heavy_scorpion',
    strong_against: ['infantry', 'archer'],
    weak_against: ['cavalry', 'knight', 'building'],
  },

  heavy_scorpion: {
    name: 'Heavy Scorpion',
    type: 'heavy_scorpion',
    category: 'siege',
    age: 'imperial_age',
    hp: 50,
    attack: 16,
    meleeArmor: 0,
    pierceArmor: 8,
    speed: 0.65,
    range: 7,
    attackSpeed: 3.6,
    lineOfSight: 9,
    cost: { wood: 75, gold: 75 },
    trainTime: 30,
    population: 2,
    trainingBuilding: 'siege_workshop',
    strong_against: ['infantry', 'archer'],
    weak_against: ['cavalry', 'knight', 'building'],
  },
}

export function getUnitConfig(unitType: string): UnitConfig | undefined {
  return UNITS[unitType]
}

export function getUnitsByAge(age: string): UnitConfig[] {
  return Object.values(UNITS).filter((unit) => unit.age === age)
}

export function getUnitsByCategory(category: string): UnitConfig[] {
  return Object.values(UNITS).filter((unit) => unit.category === category)
}

export function getAllUnits(): UnitConfig[] {
  return Object.values(UNITS)
}
